# Generated by Django 4.1.3 on 2022-12-03 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=250)),
                ('size', models.CharField(blank=True, max_length=250, null=True)),
                ('value', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('casa', 'casa'), ('apartamento ', 'apartamento')], default='casa', max_length=250)),
                ('furnished', models.BooleanField(default=False)),
                ('pets', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('morning_sun', models.BooleanField(default=False)),
                ('guarantor', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='GET_HOUSE/static_files/')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='clients.client')),
            ],
            options={
                'db_table': 'interests',
            },
        ),
    ]
