# Generated by Django 4.1.3 on 2023-02-08 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import apps.interests.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=250)),
                ('size', models.CharField(blank=True, max_length=250, null=True)),
                ('value', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('casa', 'casa'), ('apartamento ', 'apartamento')], default='casa', max_length=250)),
                ('furnished', models.BooleanField(default=False)),
                ('pets', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('morning_sun', models.BooleanField(default=False)),
                ('guarantor', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to=apps.interests.models.content_file_name)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interests',
            },
        ),
    ]
