# Generated by Django 4.1.3 on 2023-03-14 12:49

import apps.interests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interests',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.interests.models.content_file_name),
        ),
        migrations.AlterField(
            model_name='interests',
            name='type',
            field=models.CharField(choices=[('casa', 'casa'), ('apartamento', 'apartamento')], default='casa', max_length=250),
        ),
    ]
