# Generated by Django 4.1.3 on 2023-04-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0002_alter_interests_file_alter_interests_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='interests',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='interests',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='interests',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
