# Generated by Django 4.1.3 on 2022-12-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('inquilino', 'inquilino'), ('proprietário ', 'proprietário ')], default='inquilino', max_length=250)),
                ('secret', models.CharField(max_length=250)),
                ('key', models.CharField(max_length=250, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
    ]
