# Generated by Django 4.1.3 on 2022-12-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(blank=True, choices=[('comprador', 'comprador'), ('vendedor', 'vendedor')], default='comprador', max_length=250, null=True)),
                ('secret', models.CharField(blank=True, max_length=250, null=True)),
                ('key', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
    ]
