# Generated by Django 4.1.3 on 2023-03-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('inquilino', 'inquilino'), ('proprietário ', 'proprietário ')], default='inquilino', max_length=250),
        ),
    ]
