# Generated by Django 4.1.3 on 2023-04-05 23:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarbageTokenModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('refresh', models.TextField()),
            ],
            options={
                'db_table': 'garbage_token',
            },
        ),
    ]
