# Generated by Django 4.1.3 on 2023-04-18 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_garbagetokenmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GarbageTokenModel',
        ),
    ]
